/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package io.github.kokkiemouse.translationcli_s

import io.github.kokkiemouse.translationcli_s.excite.ExciteTranslate

object App {
  def main(args: Array[String]): Unit = {
    var excitetrans=new ExciteTranslate("ENJA");
    for(arg <- args ){
      println("Result : " + excitetrans.getTranslatedText(arg))
    }
  }
}
